### ISSUE TITLE
Drop movies with no poster path

### ISSUE THREAD

**Issue by nathancday** [o19s/tmdb_dump#2]
Probably don't need to keep these in the JSON. Thought being if they don't have poster they are not the kind of movies we are after.

**Comment by epugh** [comment]
I *think* @nathancday that this is done, with the check in `scrub_and_shrink.py`: `dat["poster_path"] is not None`

**Comment by epugh** [comment]
I'm going to close this for now, but please reopen it if I am not understanding.
