### ISSUE TITLE
I was poking at Dan's search viz, and I think we need to scrub our tmdb data a bit more...

### ISSUE THREAD

**Issue by epugh** [o19s/tmdb_dump#4]
Go to http://search-viz.dev.o19s.com:81/#!/ and search for Zombies..  It may be super specific to Zombies, as a query, but what we get is a bunch of garbage....

I looked in splainer:

http://splainer.io/#?solr=http:%2F%2Fquepid-solr.dev.o19s.com:8985%2Fsolr%2Ftmdb%2Fselect%3Fq%3Dtitle:zombie%20ANd%20title:Corona%26fl%3Dtitle%20id%20vote_count&fieldSpec=title%20id%20vote_count

We currenlty look for a `vote_count` greater than zero, but I think maybe, to have recognizable movies, we need to do a higher vote_count.

https://github.com/o19s/tmdb_dump/blob/master/scrub_and_shrink.py#L33

I'm thinking, in poking around, that having a vote_count of 100, might help.  lots of crap zombie movies!  I did star wars, and shocking how much crap out there as well.

Alternatively, maybe @worleydl you want search viz to filter to vote_count > 100?

**Comment by worleydl** [comment]
Yes that's an option.  The current query is kinda busted in searchviz,
heavy boosts on title, no way of knowing the degree of genres so there's a
lot of noise.  My goto of bruce willis movies got busted because the roast
of bruce willis conquers all with the title boost now.

**Comment by worleydl** [comment]
A popularity slider based on vote_count would be nice.  Then you can find
your favorite actors worst movies!
